config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'about'    => 'static_pages#about'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts media-list">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items%>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: {multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "Compose new micropost...", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn btn-primary btn-block" %>
  </div>
  <div class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </div>
<% end %>

<script>
  $("#micropost_picture").bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB, Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="row">
  <div class="col-xs-6">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat"><%= @user.following.count %></strong>
      <span class="small">following</span>
    </a>
  </div>
  <div class="col-xs-6">
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat"><%= @user.followers.count %></strong>
      <span class="small">followers</span>
    </a>
  </div>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <%= link_to gravatar_for(current_user, size: 50), current_user %>
  <%= current_user.name %>
</h1>
<div><%= link_to "view my profile", current_user %></div>
<div><%= pluralize(current_user.microposts.count, "micropost") %></div>